// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/resources.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public interface AnnotationBoundaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The index in the sequence of transcribed pieces of the conversation where
   * the boundary is located.
   * </pre>
   *
   * <code>int32 transcript_index = 1;</code>
   * @return The transcriptIndex.
   */
  int getTranscriptIndex();

  /**
   * <pre>
   * The time offset of this boundary with respect to the start time of the
   * first word in the transcript piece.
   * </pre>
   *
   * <code>.google.protobuf.Duration time_offset = 2;</code>
   * @return Whether the timeOffset field is set.
   */
  boolean hasTimeOffset();
  /**
   * <pre>
   * The time offset of this boundary with respect to the start time of the
   * first word in the transcript piece.
   * </pre>
   *
   * <code>.google.protobuf.Duration time_offset = 2;</code>
   * @return The timeOffset.
   */
  com.google.protobuf.Duration getTimeOffset();
  /**
   * <pre>
   * The time offset of this boundary with respect to the start time of the
   * first word in the transcript piece.
   * </pre>
   *
   * <code>.google.protobuf.Duration time_offset = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getTimeOffsetOrBuilder();

  /**
   * <pre>
   * The word index of this boundary with respect to the first word in the
   * transcript piece.
   * </pre>
   *
   * <code>int32 word_index = 3;</code>
   * @return The wordIndex.
   */
  int getWordIndex();

  public com.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary.DetailedBoundaryCase getDetailedBoundaryCase();
}
