// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/resources.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public interface CallAnnotationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1alpha1.CallAnnotation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The channel of the audio where the annotation occurs. For single-channel
   * audio, this field is not populated.
   * </pre>
   *
   * <code>int32 channel_tag = 1;</code>
   * @return The channelTag.
   */
  int getChannelTag();

  /**
   * <pre>
   * ( --
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary start_boundary = 2 [deprecated = true];</code>
   * @return Whether the startBoundary field is set.
   */
  @java.lang.Deprecated boolean hasStartBoundary();
  /**
   * <pre>
   * ( --
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary start_boundary = 2 [deprecated = true];</code>
   * @return The startBoundary.
   */
  @java.lang.Deprecated com.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary getStartBoundary();
  /**
   * <pre>
   * ( --
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary start_boundary = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.BoundaryOrBuilder getStartBoundaryOrBuilder();

  /**
   * <pre>
   * ( --
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary end_boundary = 3 [deprecated = true];</code>
   * @return Whether the endBoundary field is set.
   */
  @java.lang.Deprecated boolean hasEndBoundary();
  /**
   * <pre>
   * ( --
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary end_boundary = 3 [deprecated = true];</code>
   * @return The endBoundary.
   */
  @java.lang.Deprecated com.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary getEndBoundary();
  /**
   * <pre>
   * ( --
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.Boundary end_boundary = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.BoundaryOrBuilder getEndBoundaryOrBuilder();

  /**
   * <pre>
   * The boundary in the call where the annotation starts, inclusive.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary annotation_start_boundary = 4;</code>
   * @return Whether the annotationStartBoundary field is set.
   */
  boolean hasAnnotationStartBoundary();
  /**
   * <pre>
   * The boundary in the call where the annotation starts, inclusive.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary annotation_start_boundary = 4;</code>
   * @return The annotationStartBoundary.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary getAnnotationStartBoundary();
  /**
   * <pre>
   * The boundary in the call where the annotation starts, inclusive.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary annotation_start_boundary = 4;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundaryOrBuilder getAnnotationStartBoundaryOrBuilder();

  /**
   * <pre>
   * The boundary in the call where the annotation ends, inclusive.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary annotation_end_boundary = 5;</code>
   * @return Whether the annotationEndBoundary field is set.
   */
  boolean hasAnnotationEndBoundary();
  /**
   * <pre>
   * The boundary in the call where the annotation ends, inclusive.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary annotation_end_boundary = 5;</code>
   * @return The annotationEndBoundary.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary getAnnotationEndBoundary();
  /**
   * <pre>
   * The boundary in the call where the annotation ends, inclusive.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundary annotation_end_boundary = 5;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.AnnotationBoundaryOrBuilder getAnnotationEndBoundaryOrBuilder();

  /**
   * <pre>
   * Data specifying an interruption.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.InterruptionData interruption_data = 10;</code>
   * @return Whether the interruptionData field is set.
   */
  boolean hasInterruptionData();
  /**
   * <pre>
   * Data specifying an interruption.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.InterruptionData interruption_data = 10;</code>
   * @return The interruptionData.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.InterruptionData getInterruptionData();
  /**
   * <pre>
   * Data specifying an interruption.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.InterruptionData interruption_data = 10;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.InterruptionDataOrBuilder getInterruptionDataOrBuilder();

  /**
   * <pre>
   * Data specifying sentiment.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.SentimentData sentiment_data = 11;</code>
   * @return Whether the sentimentData field is set.
   */
  boolean hasSentimentData();
  /**
   * <pre>
   * Data specifying sentiment.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.SentimentData sentiment_data = 11;</code>
   * @return The sentimentData.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.SentimentData getSentimentData();
  /**
   * <pre>
   * Data specifying sentiment.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.SentimentData sentiment_data = 11;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.SentimentDataOrBuilder getSentimentDataOrBuilder();

  /**
   * <pre>
   * Data specifying silence.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.SilenceData silence_data = 12;</code>
   * @return Whether the silenceData field is set.
   */
  boolean hasSilenceData();
  /**
   * <pre>
   * Data specifying silence.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.SilenceData silence_data = 12;</code>
   * @return The silenceData.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.SilenceData getSilenceData();
  /**
   * <pre>
   * Data specifying silence.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.SilenceData silence_data = 12;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.SilenceDataOrBuilder getSilenceDataOrBuilder();

  /**
   * <pre>
   * Data specifying a hold.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.HoldData hold_data = 13;</code>
   * @return Whether the holdData field is set.
   */
  boolean hasHoldData();
  /**
   * <pre>
   * Data specifying a hold.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.HoldData hold_data = 13;</code>
   * @return The holdData.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.HoldData getHoldData();
  /**
   * <pre>
   * Data specifying a hold.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.HoldData hold_data = 13;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.HoldDataOrBuilder getHoldDataOrBuilder();

  /**
   * <pre>
   * Data specifying an entity mention.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.EntityMentionData entity_mention_data = 15;</code>
   * @return Whether the entityMentionData field is set.
   */
  boolean hasEntityMentionData();
  /**
   * <pre>
   * Data specifying an entity mention.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.EntityMentionData entity_mention_data = 15;</code>
   * @return The entityMentionData.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.EntityMentionData getEntityMentionData();
  /**
   * <pre>
   * Data specifying an entity mention.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.EntityMentionData entity_mention_data = 15;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.EntityMentionDataOrBuilder getEntityMentionDataOrBuilder();

  public com.google.cloud.contactcenterinsights.v1alpha1.CallAnnotation.DataCase getDataCase();
}
