// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/contact_center_insights.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public final class ContactCenterInsightsProto {
  private ContactCenterInsightsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisOperationMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateConversationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateConversationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GetConversationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_GetConversationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_UpdateConversationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_UpdateConversationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteConversationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteConversationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GetAnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_GetAnalysisRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteAnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteAnalysisRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_BigQueryDestination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_BigQueryDestination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nIgoogle/cloud/contactcenterinsights/v1a" +
      "lpha1/contact_center_insights.proto\022+goo" +
      "gle.cloud.contactcenterinsights.v1alpha1" +
      "\032\034google/api/annotations.proto\032\027google/a" +
      "pi/client.proto\032\037google/api/field_behavi" +
      "or.proto\032\031google/api/resource.proto\032;goo" +
      "gle/cloud/contactcenterinsights/v1alpha1" +
      "/resources.proto\032#google/longrunning/ope" +
      "rations.proto\032\036google/protobuf/duration." +
      "proto\032\033google/protobuf/empty.proto\032 goog" +
      "le/protobuf/field_mask.proto\032\037google/pro" +
      "tobuf/timestamp.proto\032\027google/rpc/status" +
      ".proto\"\333\001\n\037CreateAnalysisOperationMetada" +
      "ta\0224\n\013create_time\030\001 \001(\0132\032.google.protobu" +
      "f.TimestampB\003\340A\003\0221\n\010end_time\030\002 \001(\0132\032.goo" +
      "gle.protobuf.TimestampB\003\340A\003\022O\n\014conversat" +
      "ion\030\003 \001(\tB9\340A\003\372A3\n1contactcenterinsights" +
      ".googleapis.com/Conversation\"\305\001\n\031CreateC" +
      "onversationRequest\0229\n\006parent\030\001 \001(\tB)\340A\002\372" +
      "A#\n!locations.googleapis.com/Location\022T\n" +
      "\014conversation\030\002 \001(\01329.google.cloud.conta" +
      "ctcenterinsights.v1alpha1.ConversationB\003" +
      "\340A\002\022\027\n\017conversation_id\030\003 \001(\t\"\214\001\n\030ListCon" +
      "versationsRequest\0229\n\006parent\030\001 \001(\tB)\340A\002\372A" +
      "#\n!locations.googleapis.com/Location\022\021\n\t" +
      "page_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t\022\016\n\006f" +
      "ilter\030\004 \001(\t\"\206\001\n\031ListConversationsRespons" +
      "e\022P\n\rconversations\030\001 \003(\01329.google.cloud." +
      "contactcenterinsights.v1alpha1.Conversat" +
      "ion\022\027\n\017next_page_token\030\002 \001(\t\"a\n\026GetConve" +
      "rsationRequest\022G\n\004name\030\001 \001(\tB9\340A\002\372A3\n1co" +
      "ntactcenterinsights.googleapis.com/Conve" +
      "rsation\"\242\001\n\031UpdateConversationRequest\022T\n" +
      "\014conversation\030\001 \001(\01329.google.cloud.conta" +
      "ctcenterinsights.v1alpha1.ConversationB\003" +
      "\340A\002\022/\n\013update_mask\030\002 \001(\0132\032.google.protob" +
      "uf.FieldMask\"s\n\031DeleteConversationReques" +
      "t\022G\n\004name\030\001 \001(\tB9\340A\002\372A3\n1contactcenterin" +
      "sights.googleapis.com/Conversation\022\r\n\005fo" +
      "rce\030\002 \001(\010\"\260\001\n\025CreateAnalysisRequest\022I\n\006p" +
      "arent\030\001 \001(\tB9\340A\002\372A3\n1contactcenterinsigh" +
      "ts.googleapis.com/Conversation\022L\n\010analys" +
      "is\030\002 \001(\01325.google.cloud.contactcenterins" +
      "ights.v1alpha1.AnalysisB\003\340A\002\"\247\001\n\023ListAna" +
      "lysesRequest\022I\n\006parent\030\001 \001(\tB9\340A\002\372A3\n1co" +
      "ntactcenterinsights.googleapis.com/Conve" +
      "rsation\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token" +
      "\030\003 \001(\t\022\016\n\006filter\030\004 \001(\t\022\016\n\006latest\030\005 \001(\010\"x" +
      "\n\024ListAnalysesResponse\022G\n\010analyses\030\001 \003(\013" +
      "25.google.cloud.contactcenterinsights.v1" +
      "alpha1.Analysis\022\027\n\017next_page_token\030\002 \001(\t" +
      "\"Y\n\022GetAnalysisRequest\022C\n\004name\030\001 \001(\tB5\340A" +
      "\002\372A/\n-contactcenterinsights.googleapis.c" +
      "om/Analysis\"\\\n\025DeleteAnalysisRequest\022C\n\004" +
      "name\030\001 \001(\tB5\340A\002\372A/\n-contactcenterinsight" +
      "s.googleapis.com/Analysis\"\236\002\n\031ExportInsi" +
      "ghtsDataRequest\0229\n\006parent\030\001 \001(\tB)\340A\002\372A#\n" +
      "!locations.googleapis.com/Location\022{\n\025bi" +
      "g_query_destination\030\002 \001(\0132Z.google.cloud" +
      ".contactcenterinsights.v1alpha1.ExportIn" +
      "sightsDataRequest.BigQueryDestinationH\000\032" +
      ":\n\023BigQueryDestination\022\024\n\007dataset\030\001 \001(\tB" +
      "\003\340A\002\022\r\n\005table\030\002 \001(\tB\r\n\013destination\"\212\002\n\032E" +
      "xportInsightsDataMetadata\0224\n\013create_time" +
      "\030\001 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022" +
      "1\n\010end_time\030\002 \001(\0132\032.google.protobuf.Time" +
      "stampB\003\340A\003\022W\n\007request\030\003 \001(\0132F.google.clo" +
      "ud.contactcenterinsights.v1alpha1.Export" +
      "InsightsDataRequest\022*\n\016partial_errors\030\004 " +
      "\003(\0132\022.google.rpc.Status\"\034\n\032ExportInsight" +
      "sDataResponse2\275\023\n\025ContactCenterInsights\022" +
      "\214\002\n\022CreateConversation\022F.google.cloud.co" +
      "ntactcenterinsights.v1alpha1.CreateConve" +
      "rsationRequest\0329.google.cloud.contactcen" +
      "terinsights.v1alpha1.Conversation\"s\202\323\344\223\002" +
      "G\"7/v1alpha1/{parent=projects/*/location" +
      "s/*}/conversations:\014conversation\332A#paren" +
      "t,conversation,conversation_id\022\216\002\n\022Updat" +
      "eConversation\022F.google.cloud.contactcent" +
      "erinsights.v1alpha1.UpdateConversationRe" +
      "quest\0329.google.cloud.contactcenterinsigh" +
      "ts.v1alpha1.Conversation\"u\202\323\344\223\002T2D/v1alp" +
      "ha1/{conversation.name=projects/*/locati" +
      "ons/*/conversations/*}:\014conversation\332A\030c" +
      "onversation,update_mask\022\331\001\n\017GetConversat" +
      "ion\022C.google.cloud.contactcenterinsights" +
      ".v1alpha1.GetConversationRequest\0329.googl" +
      "e.cloud.contactcenterinsights.v1alpha1.C" +
      "onversation\"F\202\323\344\223\0029\0227/v1alpha1/{name=pro" +
      "jects/*/locations/*/conversations/*}\332A\004n" +
      "ame\022\354\001\n\021ListConversations\022E.google.cloud" +
      ".contactcenterinsights.v1alpha1.ListConv" +
      "ersationsRequest\032F.google.cloud.contactc" +
      "enterinsights.v1alpha1.ListConversations" +
      "Response\"H\202\323\344\223\0029\0227/v1alpha1/{parent=proj" +
      "ects/*/locations/*}/conversations\332A\006pare" +
      "nt\022\274\001\n\022DeleteConversation\022F.google.cloud" +
      ".contactcenterinsights.v1alpha1.DeleteCo" +
      "nversationRequest\032\026.google.protobuf.Empt" +
      "y\"F\202\323\344\223\0029*7/v1alpha1/{name=projects/*/lo" +
      "cations/*/conversations/*}\332A\004name\022\212\002\n\016Cr" +
      "eateAnalysis\022B.google.cloud.contactcente" +
      "rinsights.v1alpha1.CreateAnalysisRequest" +
      "\032\035.google.longrunning.Operation\"\224\001\202\323\344\223\002N" +
      "\"B/v1alpha1/{parent=projects/*/locations" +
      "/*/conversations/*}/analyses:\010analysis\332A" +
      "\017parent,analysis\312A+\n\010Analysis\022\037CreateAna" +
      "lysisOperationMetadata\022\330\001\n\013GetAnalysis\022?" +
      ".google.cloud.contactcenterinsights.v1al" +
      "pha1.GetAnalysisRequest\0325.google.cloud.c" +
      "ontactcenterinsights.v1alpha1.Analysis\"Q" +
      "\202\323\344\223\002D\022B/v1alpha1/{name=projects/*/locat" +
      "ions/*/conversations/*/analyses/*}\332A\004nam" +
      "e\022\350\001\n\014ListAnalyses\022@.google.cloud.contac" +
      "tcenterinsights.v1alpha1.ListAnalysesReq" +
      "uest\032A.google.cloud.contactcenterinsight" +
      "s.v1alpha1.ListAnalysesResponse\"S\202\323\344\223\002D\022" +
      "B/v1alpha1/{parent=projects/*/locations/" +
      "*/conversations/*}/analyses\332A\006parent\022\277\001\n" +
      "\016DeleteAnalysis\022B.google.cloud.contactce" +
      "nterinsights.v1alpha1.DeleteAnalysisRequ" +
      "est\032\026.google.protobuf.Empty\"Q\202\323\344\223\002D*B/v1" +
      "alpha1/{name=projects/*/locations/*/conv" +
      "ersations/*/analyses/*}\332A\004name\022\212\002\n\022Expor" +
      "tInsightsData\022F.google.cloud.contactcent" +
      "erinsights.v1alpha1.ExportInsightsDataRe" +
      "quest\032\035.google.longrunning.Operation\"\214\001\202" +
      "\323\344\223\002B\"=/v1alpha1/{parent=projects/*/loca" +
      "tions/*}/insightsdata:export:\001*\332A\006parent" +
      "\312A8\n\032ExportInsightsDataResponse\022\032ExportI" +
      "nsightsDataMetadata\032X\312A$contactcenterins" +
      "ights.googleapis.com\322A.https://www.googl" +
      "eapis.com/auth/cloud-platformB\261\001\n/com.go" +
      "ogle.cloud.contactcenterinsights.v1alpha" +
      "1B\032ContactCenterInsightsProtoP\001Z`google." +
      "golang.org/genproto/googleapis/cloud/con" +
      "tactcenterinsights/v1alpha1;contactcente" +
      "rinsightsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.cloud.contactcenterinsights.v1alpha1.ResourcesProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisOperationMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisOperationMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisOperationMetadata_descriptor,
        new java.lang.String[] { "CreateTime", "EndTime", "Conversation", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateConversationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateConversationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateConversationRequest_descriptor,
        new java.lang.String[] { "Parent", "Conversation", "ConversationId", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", "Filter", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ListConversationsResponse_descriptor,
        new java.lang.String[] { "Conversations", "NextPageToken", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GetConversationRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GetConversationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_GetConversationRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_UpdateConversationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_UpdateConversationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_UpdateConversationRequest_descriptor,
        new java.lang.String[] { "Conversation", "UpdateMask", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteConversationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteConversationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteConversationRequest_descriptor,
        new java.lang.String[] { "Name", "Force", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_CreateAnalysisRequest_descriptor,
        new java.lang.String[] { "Parent", "Analysis", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", "Filter", "Latest", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ListAnalysesResponse_descriptor,
        new java.lang.String[] { "Analyses", "NextPageToken", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GetAnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GetAnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_GetAnalysisRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteAnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteAnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_DeleteAnalysisRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_descriptor,
        new java.lang.String[] { "Parent", "BigQueryDestination", "Destination", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_BigQueryDestination_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_BigQueryDestination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataRequest_BigQueryDestination_descriptor,
        new java.lang.String[] { "Dataset", "Table", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataMetadata_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataMetadata_descriptor,
        new java.lang.String[] { "CreateTime", "EndTime", "Request", "PartialErrors", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ExportInsightsDataResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.contactcenterinsights.v1alpha1.ResourcesProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
