// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/resources.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public interface ConversationDataSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1alpha1.ConversationDataSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A Cloud Storage location specification for the audio and transcript.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.GcsSource gcs_source = 1;</code>
   * @return Whether the gcsSource field is set.
   */
  boolean hasGcsSource();
  /**
   * <pre>
   * A Cloud Storage location specification for the audio and transcript.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.GcsSource gcs_source = 1;</code>
   * @return The gcsSource.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.GcsSource getGcsSource();
  /**
   * <pre>
   * A Cloud Storage location specification for the audio and transcript.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.GcsSource gcs_source = 1;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.GcsSourceOrBuilder getGcsSourceOrBuilder();

  public com.google.cloud.contactcenterinsights.v1alpha1.ConversationDataSource.SourceCase getSourceCase();
}
