// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/resources.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public interface ConversationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1alpha1.Conversation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Immutable. The resource name of the conversation.
   * Format:
   * projects/{project}/locations/{location}/conversations/{conversation}
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Immutable. The resource name of the conversation.
   * Format:
   * projects/{project}/locations/{location}/conversations/{conversation}
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Immutable. The source of the audio and transcription for the conversation.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.ConversationDataSource data_source = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return Whether the dataSource field is set.
   */
  boolean hasDataSource();
  /**
   * <pre>
   * Immutable. The source of the audio and transcription for the conversation.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.ConversationDataSource data_source = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The dataSource.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.ConversationDataSource getDataSource();
  /**
   * <pre>
   * Immutable. The source of the audio and transcription for the conversation.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.ConversationDataSource data_source = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.ConversationDataSourceOrBuilder getDataSourceOrBuilder();

  /**
   * <pre>
   * Output only. The time at which this conversation was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   * Output only. The time at which this conversation was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   * Output only. The time at which this conversation was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   * Output only. The most recent time at which the conversation was updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <pre>
   * Output only. The most recent time at which the conversation was updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <pre>
   * Output only. The most recent time at which the conversation was updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   * <pre>
   * An opaque, user-specified string representing the human agent who handled
   * the conversation.
   * </pre>
   *
   * <code>string agent_id = 5;</code>
   * @return The agentId.
   */
  java.lang.String getAgentId();
  /**
   * <pre>
   * An opaque, user-specified string representing the human agent who handled
   * the conversation.
   * </pre>
   *
   * <code>string agent_id = 5;</code>
   * @return The bytes for agentId.
   */
  com.google.protobuf.ByteString
      getAgentIdBytes();

  /**
   * <pre>
   * A map for the user to specify any custom fields.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 6;</code>
   */
  int getLabelsCount();
  /**
   * <pre>
   * A map for the user to specify any custom fields.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 6;</code>
   */
  boolean containsLabels(
      java.lang.String key);
  /**
   * Use {@link #getLabelsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getLabels();
  /**
   * <pre>
   * A map for the user to specify any custom fields.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getLabelsMap();
  /**
   * <pre>
   * A map for the user to specify any custom fields.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 6;</code>
   */

  java.lang.String getLabelsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * A map for the user to specify any custom fields.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 6;</code>
   */

  java.lang.String getLabelsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Call-specific metadata.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.CallMetadata call_metadata = 7;</code>
   * @return Whether the callMetadata field is set.
   */
  boolean hasCallMetadata();
  /**
   * <pre>
   * Call-specific metadata.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.CallMetadata call_metadata = 7;</code>
   * @return The callMetadata.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.Conversation.CallMetadata getCallMetadata();
  /**
   * <pre>
   * Call-specific metadata.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.CallMetadata call_metadata = 7;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.Conversation.CallMetadataOrBuilder getCallMetadataOrBuilder();

  /**
   * <pre>
   * Output only. The conversation transcript.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.Transcript transcript = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the transcript field is set.
   */
  boolean hasTranscript();
  /**
   * <pre>
   * Output only. The conversation transcript.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.Transcript transcript = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The transcript.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.Conversation.Transcript getTranscript();
  /**
   * <pre>
   * Output only. The conversation transcript.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.Transcript transcript = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.Conversation.TranscriptOrBuilder getTranscriptOrBuilder();

  /**
   * <pre>
   * Immutable. The conversation medium.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.Medium medium = 9 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The enum numeric value on the wire for medium.
   */
  int getMediumValue();
  /**
   * <pre>
   * Immutable. The conversation medium.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Conversation.Medium medium = 9 [(.google.api.field_behavior) = IMMUTABLE];</code>
   * @return The medium.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.Conversation.Medium getMedium();

  /**
   * <pre>
   * Output only. The duration of the conversation.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the duration field is set.
   */
  boolean hasDuration();
  /**
   * <pre>
   * Output only. The duration of the conversation.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The duration.
   */
  com.google.protobuf.Duration getDuration();
  /**
   * <pre>
   * Output only. The duration of the conversation.
   * </pre>
   *
   * <code>.google.protobuf.Duration duration = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder();

  /**
   * <pre>
   * Output only. The number of turns in the conversation.
   * </pre>
   *
   * <code>int32 turn_count = 11 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The turnCount.
   */
  int getTurnCount();

  /**
   * <pre>
   * Output only. The conversation's latest analysis, if one exists.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Analysis latest_analysis = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the latestAnalysis field is set.
   */
  boolean hasLatestAnalysis();
  /**
   * <pre>
   * Output only. The conversation's latest analysis, if one exists.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Analysis latest_analysis = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The latestAnalysis.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.Analysis getLatestAnalysis();
  /**
   * <pre>
   * Output only. The conversation's latest analysis, if one exists.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.Analysis latest_analysis = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.AnalysisOrBuilder getLatestAnalysisOrBuilder();

  public com.google.cloud.contactcenterinsights.v1alpha1.Conversation.MetadataCase getMetadataCase();
}
