// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/contact_center_insights.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public interface ExportInsightsDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The parent resource to export data from.
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. The parent resource to export data from.
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * Specified if sink is a BigQuery table.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest.BigQueryDestination big_query_destination = 2;</code>
   * @return Whether the bigQueryDestination field is set.
   */
  boolean hasBigQueryDestination();
  /**
   * <pre>
   * Specified if sink is a BigQuery table.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest.BigQueryDestination big_query_destination = 2;</code>
   * @return The bigQueryDestination.
   */
  com.google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest.BigQueryDestination getBigQueryDestination();
  /**
   * <pre>
   * Specified if sink is a BigQuery table.
   * </pre>
   *
   * <code>.google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest.BigQueryDestination big_query_destination = 2;</code>
   */
  com.google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest.BigQueryDestinationOrBuilder getBigQueryDestinationOrBuilder();

  public com.google.cloud.contactcenterinsights.v1alpha1.ExportInsightsDataRequest.DestinationCase getDestinationCase();
}
