// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/contactcenterinsights/v1alpha1/resources.proto

package com.google.cloud.contactcenterinsights.v1alpha1;

public final class ResourcesProto {
  private ResourcesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_CallMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_CallMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_WordInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Analysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Analysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationDataSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationDataSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GcsSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_GcsSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationLevelSentiment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationLevelSentiment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_Boundary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_Boundary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnnotationBoundary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_AnnotationBoundary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_MetadataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_InterruptionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_InterruptionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_SilenceData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_SilenceData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_HoldData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_HoldData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_EntityMentionData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_EntityMentionData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_contactcenterinsights_v1alpha1_SentimentData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_contactcenterinsights_v1alpha1_SentimentData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;google/cloud/contactcenterinsights/v1a" +
      "lpha1/resources.proto\022+google.cloud.cont" +
      "actcenterinsights.v1alpha1\032\037google/api/f" +
      "ield_behavior.proto\032\031google/api/resource" +
      ".proto\032\036google/protobuf/duration.proto\032\037" +
      "google/protobuf/timestamp.proto\032\034google/" +
      "api/annotations.proto\"\251\014\n\014Conversation\022\021" +
      "\n\004name\030\001 \001(\tB\003\340A\005\022]\n\013data_source\030\002 \001(\0132C" +
      ".google.cloud.contactcenterinsights.v1al" +
      "pha1.ConversationDataSourceB\003\340A\005\0224\n\013crea" +
      "te_time\030\003 \001(\0132\032.google.protobuf.Timestam" +
      "pB\003\340A\003\0224\n\013update_time\030\004 \001(\0132\032.google.pro" +
      "tobuf.TimestampB\003\340A\003\022\020\n\010agent_id\030\005 \001(\t\022U" +
      "\n\006labels\030\006 \003(\0132E.google.cloud.contactcen" +
      "terinsights.v1alpha1.Conversation.Labels" +
      "Entry\022_\n\rcall_metadata\030\007 \001(\0132F.google.cl" +
      "oud.contactcenterinsights.v1alpha1.Conve" +
      "rsation.CallMetadataH\000\022]\n\ntranscript\030\010 \001" +
      "(\0132D.google.cloud.contactcenterinsights." +
      "v1alpha1.Conversation.TranscriptB\003\340A\003\022U\n" +
      "\006medium\030\t \001(\0162@.google.cloud.contactcent" +
      "erinsights.v1alpha1.Conversation.MediumB" +
      "\003\340A\005\0220\n\010duration\030\n \001(\0132\031.google.protobuf" +
      ".DurationB\003\340A\003\022\027\n\nturn_count\030\013 \001(\005B\003\340A\003\022" +
      "S\n\017latest_analysis\030\014 \001(\01325.google.cloud." +
      "contactcenterinsights.v1alpha1.AnalysisB" +
      "\003\340A\003\032?\n\014CallMetadata\022\030\n\020customer_channel" +
      "\030\001 \001(\005\022\025\n\ragent_channel\030\002 \001(\005\032\344\003\n\nTransc" +
      "ript\022s\n\023transcript_segments\030\001 \003(\0132V.goog" +
      "le.cloud.contactcenterinsights.v1alpha1." +
      "Conversation.Transcript.TranscriptSegmen" +
      "t\032\340\002\n\021TranscriptSegment\022\014\n\004text\030\001 \001(\t\022\022\n" +
      "\nconfidence\030\002 \001(\002\022n\n\005words\030\003 \003(\0132_.googl" +
      "e.cloud.contactcenterinsights.v1alpha1.C" +
      "onversation.Transcript.TranscriptSegment" +
      ".WordInfo\022\025\n\rlanguage_code\030\004 \001(\t\022\023\n\013chan" +
      "nel_tag\030\005 \001(\005\032\214\001\n\010WordInfo\022/\n\014start_offs" +
      "et\030\001 \001(\0132\031.google.protobuf.Duration\022-\n\ne" +
      "nd_offset\030\002 \001(\0132\031.google.protobuf.Durati" +
      "on\022\014\n\004word\030\003 \001(\t\022\022\n\nconfidence\030\004 \001(\002\032-\n\013" +
      "LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\":\n\006Medium\022\026\n\022MEDIUM_UNSPECIFIED\020\000\022\016\n" +
      "\nPHONE_CALL\020\001\022\010\n\004CHAT\020\002:|\352Ay\n1contactcen" +
      "terinsights.googleapis.com/Conversation\022" +
      "Dprojects/{project}/locations/{location}" +
      "/conversations/{conversation}B\n\n\010metadat" +
      "a\"\365\002\n\010Analysis\022\021\n\004name\030\001 \001(\tB\003\340A\005\0225\n\014req" +
      "uest_time\030\002 \001(\0132\032.google.protobuf.Timest" +
      "ampB\003\340A\003\0224\n\013create_time\030\003 \001(\0132\032.google.p" +
      "rotobuf.TimestampB\003\340A\003\022Y\n\017analysis_resul" +
      "t\030\007 \001(\0132;.google.cloud.contactcenterinsi" +
      "ghts.v1alpha1.AnalysisResultB\003\340A\003:\215\001\352A\211\001" +
      "\n-contactcenterinsights.googleapis.com/A" +
      "nalysis\022Xprojects/{project}/locations/{l" +
      "ocation}/conversations/{conversation}/an" +
      "alyses/{analysis}\"p\n\026ConversationDataSou" +
      "rce\022L\n\ngcs_source\030\001 \001(\01326.google.cloud.c" +
      "ontactcenterinsights.v1alpha1.GcsSourceH" +
      "\000B\010\n\006source\"6\n\tGcsSource\022\021\n\taudio_uri\030\001 " +
      "\001(\t\022\026\n\016transcript_uri\030\002 \001(\t\"\220\005\n\016Analysis" +
      "Result\022,\n\010end_time\030\001 \001(\0132\032.google.protob" +
      "uf.Timestamp\022r\n\026call_analysis_metadata\030\002" +
      " \001(\0132P.google.cloud.contactcenterinsight" +
      "s.v1alpha1.AnalysisResult.CallAnalysisMe" +
      "tadataH\000\032\317\003\n\024CallAnalysisMetadata\0221\n\016tot" +
      "al_duration\030\001 \001(\0132\031.google.protobuf.Dura" +
      "tion\022P\n\013annotations\030\002 \003(\0132;.google.cloud" +
      ".contactcenterinsights.v1alpha1.CallAnno" +
      "tation\022p\n\010entities\030\003 \003(\0132^.google.cloud." +
      "contactcenterinsights.v1alpha1.AnalysisR" +
      "esult.CallAnalysisMetadata.EntitiesEntry" +
      "\022Z\n\tsentiment\030\004 \003(\0132G.google.cloud.conta" +
      "ctcenterinsights.v1alpha1.ConversationLe" +
      "velSentiment\032d\n\rEntitiesEntry\022\013\n\003key\030\001 \001" +
      "(\t\022B\n\005value\030\002 \001(\01323.google.cloud.contact" +
      "centerinsights.v1alpha1.Entity:\0028\001B\n\n\010me" +
      "tadata\"\205\001\n\032ConversationLevelSentiment\022\023\n" +
      "\013channel_tag\030\001 \001(\005\022R\n\016sentiment_data\030\002 \001" +
      "(\0132:.google.cloud.contactcenterinsights." +
      "v1alpha1.SentimentData\"\354\007\n\016CallAnnotatio" +
      "n\022\023\n\013channel_tag\030\001 \001(\005\022`\n\016start_boundary" +
      "\030\002 \001(\0132D.google.cloud.contactcenterinsig" +
      "hts.v1alpha1.CallAnnotation.BoundaryB\002\030\001" +
      "\022^\n\014end_boundary\030\003 \001(\0132D.google.cloud.co" +
      "ntactcenterinsights.v1alpha1.CallAnnotat" +
      "ion.BoundaryB\002\030\001\022b\n\031annotation_start_bou" +
      "ndary\030\004 \001(\0132?.google.cloud.contactcenter" +
      "insights.v1alpha1.AnnotationBoundary\022`\n\027" +
      "annotation_end_boundary\030\005 \001(\0132?.google.c" +
      "loud.contactcenterinsights.v1alpha1.Anno" +
      "tationBoundary\022Z\n\021interruption_data\030\n \001(" +
      "\0132=.google.cloud.contactcenterinsights.v" +
      "1alpha1.InterruptionDataH\000\022T\n\016sentiment_" +
      "data\030\013 \001(\0132:.google.cloud.contactcenteri" +
      "nsights.v1alpha1.SentimentDataH\000\022P\n\014sile" +
      "nce_data\030\014 \001(\01328.google.cloud.contactcen" +
      "terinsights.v1alpha1.SilenceDataH\000\022J\n\tho" +
      "ld_data\030\r \001(\01325.google.cloud.contactcent" +
      "erinsights.v1alpha1.HoldDataH\000\022]\n\023entity" +
      "_mention_data\030\017 \001(\0132>.google.cloud.conta" +
      "ctcenterinsights.v1alpha1.EntityMentionD" +
      "ataH\000\032\205\001\n\010Boundary\022\030\n\020transcript_index\030\001" +
      " \001(\005\0220\n\013time_offset\030\002 \001(\0132\031.google.proto" +
      "buf.DurationH\000\022\024\n\nword_index\030\003 \001(\005H\000:\002\030\001" +
      "B\023\n\021detailed_boundaryB\006\n\004data\"\213\001\n\022Annota" +
      "tionBoundary\022\030\n\020transcript_index\030\001 \001(\005\0220" +
      "\n\013time_offset\030\002 \001(\0132\031.google.protobuf.Du" +
      "rationH\000\022\024\n\nword_index\030\003 \001(\005H\000B\023\n\021detail" +
      "ed_boundary\"\222\004\n\006Entity\022\024\n\014display_name\030\001" +
      " \001(\t\022F\n\004type\030\002 \001(\01628.google.cloud.contac" +
      "tcenterinsights.v1alpha1.Entity.Type\022S\n\010" +
      "metadata\030\003 \003(\0132A.google.cloud.contactcen" +
      "terinsights.v1alpha1.Entity.MetadataEntr" +
      "y\022\020\n\010salience\030\004 \001(\002\022M\n\tsentiment\030\005 \001(\0132:" +
      ".google.cloud.contactcenterinsights.v1al" +
      "pha1.SentimentData\032/\n\rMetadataEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\302\001\n\004Type\022\024\n\020" +
      "TYPE_UNSPECIFIED\020\000\022\n\n\006PERSON\020\001\022\014\n\010LOCATI" +
      "ON\020\002\022\020\n\014ORGANIZATION\020\003\022\t\n\005EVENT\020\004\022\017\n\013WOR" +
      "K_OF_ART\020\005\022\021\n\rCONSUMER_GOOD\020\006\022\t\n\005OTHER\020\007" +
      "\022\020\n\014PHONE_NUMBER\020\t\022\013\n\007ADDRESS\020\n\022\010\n\004DATE\020" +
      "\013\022\n\n\006NUMBER\020\014\022\t\n\005PRICE\020\r\"\022\n\020Interruption" +
      "Data\"\r\n\013SilenceData\"\n\n\010HoldData\"\233\002\n\021Enti" +
      "tyMentionData\022\030\n\020entity_unique_id\030\001 \001(\t\022" +
      "X\n\004type\030\002 \001(\0162J.google.cloud.contactcent" +
      "erinsights.v1alpha1.EntityMentionData.Me" +
      "ntionType\022M\n\tsentiment\030\003 \001(\0132:.google.cl" +
      "oud.contactcenterinsights.v1alpha1.Senti" +
      "mentData\"C\n\013MentionType\022\034\n\030MENTION_TYPE_" +
      "UNSPECIFIED\020\000\022\n\n\006PROPER\020\001\022\n\n\006COMMON\020\002\"1\n" +
      "\rSentimentData\022\021\n\tmagnitude\030\001 \001(\002\022\r\n\005sco" +
      "re\030\002 \001(\002B\245\001\n/com.google.cloud.contactcen" +
      "terinsights.v1alpha1B\016ResourcesProtoP\001Z`" +
      "google.golang.org/genproto/googleapis/cl" +
      "oud/contactcenterinsights/v1alpha1;conta" +
      "ctcenterinsightsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_descriptor,
        new java.lang.String[] { "Name", "DataSource", "CreateTime", "UpdateTime", "AgentId", "Labels", "CallMetadata", "Transcript", "Medium", "Duration", "TurnCount", "LatestAnalysis", "Metadata", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_CallMetadata_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_CallMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_CallMetadata_descriptor,
        new java.lang.String[] { "CustomerChannel", "AgentChannel", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_descriptor,
        new java.lang.String[] { "TranscriptSegments", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_descriptor,
        new java.lang.String[] { "Text", "Confidence", "Words", "LanguageCode", "ChannelTag", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_WordInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_Transcript_TranscriptSegment_WordInfo_descriptor,
        new java.lang.String[] { "StartOffset", "EndOffset", "Word", "Confidence", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_LabelsEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_descriptor.getNestedTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Conversation_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Analysis_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Analysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Analysis_descriptor,
        new java.lang.String[] { "Name", "RequestTime", "CreateTime", "AnalysisResult", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationDataSource_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationDataSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationDataSource_descriptor,
        new java.lang.String[] { "GcsSource", "Source", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GcsSource_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_GcsSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_GcsSource_descriptor,
        new java.lang.String[] { "AudioUri", "TranscriptUri", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_descriptor,
        new java.lang.String[] { "EndTime", "CallAnalysisMetadata", "Metadata", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_descriptor,
        new java.lang.String[] { "TotalDuration", "Annotations", "Entities", "Sentiment", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_AnalysisResult_CallAnalysisMetadata_EntitiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationLevelSentiment_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationLevelSentiment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_ConversationLevelSentiment_descriptor,
        new java.lang.String[] { "ChannelTag", "SentimentData", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_descriptor,
        new java.lang.String[] { "ChannelTag", "StartBoundary", "EndBoundary", "AnnotationStartBoundary", "AnnotationEndBoundary", "InterruptionData", "SentimentData", "SilenceData", "HoldData", "EntityMentionData", "Data", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_Boundary_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_Boundary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_CallAnnotation_Boundary_descriptor,
        new java.lang.String[] { "TranscriptIndex", "TimeOffset", "WordIndex", "DetailedBoundary", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnnotationBoundary_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_AnnotationBoundary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_AnnotationBoundary_descriptor,
        new java.lang.String[] { "TranscriptIndex", "TimeOffset", "WordIndex", "DetailedBoundary", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_descriptor,
        new java.lang.String[] { "DisplayName", "Type", "Metadata", "Salience", "Sentiment", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_MetadataEntry_descriptor =
      internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_Entity_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_InterruptionData_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_InterruptionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_InterruptionData_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_SilenceData_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_SilenceData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_SilenceData_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_HoldData_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_HoldData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_HoldData_descriptor,
        new java.lang.String[] { });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_EntityMentionData_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_EntityMentionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_EntityMentionData_descriptor,
        new java.lang.String[] { "EntityUniqueId", "Type", "Sentiment", });
    internal_static_google_cloud_contactcenterinsights_v1alpha1_SentimentData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_contactcenterinsights_v1alpha1_SentimentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_contactcenterinsights_v1alpha1_SentimentData_descriptor,
        new java.lang.String[] { "Magnitude", "Score", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
